// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type User struct {
	ID         int64
	Email      string
	FirstName  string
	LastName   string
	Password   string
	UserActive sql.NullInt64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
